### ISSUE TITLE
After usynct Complete nuget update from v8.9.3.0  to the latest v8.9.4.0 the trial period ends.

### ISSUE THREAD

**Issue by KamenovBoris** [Jumoo/uSync.Complete.Issues#106]
When updating the nuget usync complete from  v8.9.3.0  to the latest v8.9.4.0 the trial period (53 days left) was interrupted and now instead of "You are currently using a trial version of uSync Complete. It will expire in 53 days" it shows
"You licence is NoLicence" and I can't use test the product.

Before update to 8.9.4
![image](https://user-images.githubusercontent.com/7759990/114847897-dc5c2f80-9de6-11eb-9da4-8c13fd0ba6cb.png)

After update to 8.9.4
![image](https://user-images.githubusercontent.com/7759990/114847965-ebdb7880-9de6-11eb-90ec-1185721cdff4.png)

* Umbraco Version: 8.10.1
* uSync Version: v8.8.5.0 + Content Edition (v8.8.5.0), Snapshots (v8.9.3.0), Exporter (v8.9.3.0), PeopleEdition (v8.9.3.0), Publisher (v8.9.3.0), Complete (v8.9.3.0)
* Browser: Chrome

1. Install usync Complete v8.9.3.0
2. Trial is working
3. Update usync Complete to v8.9.4.0
4. Trial is no longer working, license is required

Expected behavior
The Sync trial should continue after nuget update

Thanks

**Comment by KevinJump** [comment]
Hi 

yeah we realized just after we released it - the internal trial id is tied to the version number and we upped it :( 

but the trial extender can be used to put a 30 day trial back on the site:  
http://clients.jumoo.co.uk/usync/uSyncCompeteTrialExtender.zip

**Comment by KamenovBoris** [comment]
Hi,
Thanks that worked and extended the trial to 30 days.

**Comment by JohnBergman** [comment]
Did this get included in 8.9.5, after upgrading from 8.9.3 to 8.9.5 I am still seeing the NoLicense Message. @KevinJump

**Comment by KevinJump** [comment]
It got fixed for 8.9.5 but only for people upgrading from 8.9.4+ (so the key stays the same as it was in that version). 

from 8.9.3 you would have to run the extender code. :(
